Feature/private events
notlfish/private-events pull request #2
Opened 2021-07-01 22:33 UTC by notlfish

13

2021-07-04 18:03 UTC, Georjane requested changes
### Hello, Team <STUDENTS>, ✋🏽 

Good job so far! You have a very professional Readme file, your PR is professional and you have a good mastery of git-flow. Your linters are all passing, I applaud that too.
However, we have a few more changes to make in order to meet all requirements for this project but you are almost there!

## Required Changes ♻️

- [x] After successful sign in, a user should be redirected to the Event's index page (set to `root_path` in the `Routes` file) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.\*\*png\*\*) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)) and not to create new events as it is in your app
- [x] The join event button throws an error
![image](https://user-images.githubusercontent.com/60772732/124394909-64bce300-dcf9-11eb-8db6-b51d831e52e4.png)
The event's show page displays the list of attendants but  we can't see this because of the error above

#### Controllers

##### EventsController

###### `create` action

* [x] Uses the **#build** [association refrence method](https://guides.rubyonrails.org/association_basics.html#detailed-association-reference), i.e. `current_user.events.build(event_params)` to create the new event with the user’s ID prepopulated.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

###### `index` action

* [ ] Lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] Lists upcoming events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

##### UsersController

###### `show` action

* [x] Lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] Lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] Lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [x] No notifications is been shown when a user that doesn't exist tries to sign in


Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

2021-07-05 16:55 UTC, SajjadAhmad14 commented on app/models/event.rb
> +  # end
Please remove commented code from here.

2021-07-05 16:56 UTC, SajjadAhmad14 commented on app/views/devise/mailer/email_changed.html.erb
> +<% else %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-05 16:56 UTC, SajjadAhmad14 commented on app/views/devise/passwords/edit.html.erb
> +    <% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-05 16:57 UTC, SajjadAhmad14 commented on app/views/devise/shared/_error_messages.html.erb
> +<% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-05 16:58 UTC, SajjadAhmad14 commented on app/views/layouts/application.html.erb
> +      <% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-05 16:58 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, thank you for working on changes suggested by the previous reviewer :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly.
- [ ] App is working perfectly.
## To Improve 🙏
- [x] Please remove commented code. It makes the overall codebase unclean.
- [ ] Please add the `npm install` or `yarn install` command in the Setup section and `rspec` to run tests in README.
- [ ] Please see inline comments for reference.
# Optional
- [ ] Views should be completely separate from app logic. You can move all view-related logic to app/helpers.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-05 19:48 UTC, cyonii approved these changes
## STATUS: APPROVED ✅

You have a really neat project 👏.

Congratulations 🎉, your project has been approved.
You have met the requirements for this project, you can now merge the PR.

> #### <br>Feel free to leave a comment or question if something is not clear. Slack: @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR)<br><br>

2021-07-05 20:36 UTC, merged